name: 部署 React 前端

on:
  push:
    branches: [ master ]  # 或者您的主分支名称

jobs:
  build-and-deploy:  # 构建和部署
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: 安装依赖
      run: npm ci

    - name: 构建项目
      run: npm run build

    - name: 设置 SSH 密钥
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keygen -y -f ~/.ssh/deploy_key > ~/.ssh/deploy_key.pub

    - name: 部署到服务器
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-avzc --delete"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          echo "部署完成"
        SOURCE: "./build/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: '/data/aiweb/moduchat.clinet/'
        EXCLUDE: "/node_modules/, /.git/, /.github/"

    - name: 执行远程脚本
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /data/aiweb/
          docker-compose down
          docker-compose up -d

    - name: 检查部署状态
      if: failure()
      run: |
        echo "部署失败。正在检查 SSH 连接..."
        ssh -v -i ~/.ssh/deploy_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'echo "SSH 连接测试"'
