name: Deploy React Frontend

on:
  push:
    branches: [ master ]  # 或者您的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # 使用更通用的版本号

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keygen -y -f ~/.ssh/deploy_key > ~/.ssh/deploy_key.pub

    - name: Verify SSH key
      run: ssh-keygen -l -f ~/.ssh/deploy_key

    - name: Setup SSH agent
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add ~/.ssh/deploy_key

    - name: Debug SSH connection
      run: |
        ssh -vvv -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'echo "SSH connection successful"'

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-avzr --delete -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
        SOURCE: "./build/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: '/data/aiweb/moduchat.clinet/'
        EXCLUDE: "/node_modules/"

    - name: Execute remote script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /data/aiweb/
          docker-compose up -d --build

    - name: Check deployment status
      if: failure()
      run: |
        echo "Deployment failed. Checking SSH connection..."
        ssh -v -i ~/.ssh/deploy_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'echo "SSH connection test"'